dat = [
['ACgG','anterior cingulate gyrus','ACgG'],
['AIns','anterior insula','ILa'],
['AnG','angular gyrus','AngG'],
['Calc','calcarine cortex',''],
['CgG','cingulate gyrus','CgG'],
['CO','central operculum',''],
['Cun','Cuneus','Cun'],
['Ent','entorhinal area','Ent'],
['FO','frontal operculum','fro'],
['FuG','fusiform gyrus','FuG'],
['GRe','gyrus rectus','RG'],
['IFG','inferior frontal gyrus','IFG'],
['IOG','inferior occipital gyrus','IOG'],
['ITG','inferior temporal gyrus','ITG'],
['LiG','lingual gyrus','LinG'],
['MCgG','middle cingulate gyrus',''],
['MFC','medial frontal cortex',''],
['MFG','middle frontal gyrus','MFG'],
['MOG','middle occipital gyrus',''],
['MPoG','postcentral gyrus, medial segment',''],
['MPrG','precentral gyrus, medial segment',''],
['MSFG','superior frontal gyrus, medial segment',''],
['MTG','middle temporal gyrus','MTG'],
['OFC','orbitofrontal cortex','OFC'],
['OFuG','occipital fusiform gyrus',''],
['OpIFG','opercular part of the inferior frontal gyrus','IFGOp'],
['OrIFG','orbital part of the inferior frontal gyrus','IFGOr'],
['PCgG','posterior cingulate gyrus','PCgG'],
['PCu','Precuneus','PCu'],
['PHG','parahippocampal gyrus','PHG'],
['PIns','posterior insula','ILp'],
['PO','parietal operculum','pop'],
['PoG','postcentral gyrus','PCG'],
['PP','planum polare','PT'],
['PrG','precentral gyrus','PrG'],
['PT','planum temporale','PT'],
['SCA','subcallosal area',''],
['SFG','superior frontal gyrus','SFG'],
['SMC','supplementary motor cortex','SMA'],
['SMG','supramarginal gyrus','SMG'],
['SOG','superior occipital gyrus','SOG'],
['SPL','superior parietal lobule','SPL'],
['STG','superior temporal gyrus','STG'],
['TrIFG','triangular part of the inferior frontal gyrus','IFGTr'],
['TTG','transverse temporal gyrus','TTG'],
['aals','anterior ascending ramus of the lateral sulcus','aals'],
['ahls','anterior horizontal ramus of the lateral sulcus','ahls'],
['aocs','anterior occipital sulcus','aocs'],
['cas','callosal sulcus',''],
['ccs','calcarine sulcus',''],
['cgs','cingulate sulcus','cgs'],
['cis','central insular sulcus','cis'],
['cos','collateral sulcus',''],
['crs','circular insular sulcus',''],
['cs','central sulcus','cs'],
['fms','frontomarginal sulcus',''],
['ftts','first transverse temporal sulcus',''],
['hs','Heschl\'s sulcus',''],
['ifrs','inferior frontal sulcus',''],
['ihs','interhemispheric sulcus',''],
['Itts','intermediate transverse temporal sulcus',''],
['iros','inferior rostral sulcus','iros'],
['itps','intraparietal sulcus','itps'],
['its','inferior temporal sulcus','its'],
['locs','lateral occipital sulcus','locs'],
['los','lateral orbital sulcus','los'],
['ls','lateral sulcus','ls'],
['olfs','olfactory sulcus','Olf'],
['ots','occipitotemporal sulcus',''],
['pals','posterior ascending ramus of the lateral sulcus','pals'],
['phls','posterior horizontal ramus of the lateral sulcus',''],
['pis','primary intermediate sulcus',''],
['pocs','postcentral sulcus','pocs'],
['pos','parietooccipital sulcus',''],
['prcs','precentral sulcus','prcs'],
['sbps','subparietal sulcus',''],
['sfrs','superior frontal sulcus','sfs'],
['sros','superior rostral sulcus','sros'],
['sts','superior temporal sulcus','STS'],
]